[package]
name = "flux-messages"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib/api", "lib/migration"]
resolver = "2"

[dependencies]
flux-messages-api = { path = "lib/api" }
flux-lib = { git = "https://github.com/thefluxapp/flux-lib.git" }

anyhow = "1.0.96"
thiserror = "2.0.11"
futures-lite = "2.6.0"
config = { version = "0.15", default-features = false, features = ["toml"] }
validator = { version = "0.20.0", features = ["derive"] }
uuid = { version = "1.13.2", features = ["v7"] }
chrono = "0.4.39"
log = "0.4.25"
bytes = "1.10.0"
itertools = "0.14.0"

axum = "0.7.9"

tokio = { version = "1.43.0", features = ["full"] }

prost = "0.13.5"
prost-types = "0.13.5"
tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"

async-nats = "0.39.0"

sea-orm = { version = "1.1.5", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }

serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
